export const metrics = {
  glucoseTrend: [
    { time: "08:00", value: 5.8 },
    { time: "12:30", value: 8.6 },
    { time: "15:00", value: 6.5 },
    { time: "20:40", value: 7.9 },
  ],
  sleepHours: 5.8,
  steps: 4200,
  heartRate: 78,
  missedCheckinDays: 3,
  dataSource: "示例设备数据",
};

export const reasons = [
  "晚餐后波动偏高",
  "昨晚睡眠不足",
  "连续 3 天未完成饭后步行",
];

export const defaultActions = [
  {
    category: "diet",
    title: "饮食",
    detail: "晚餐主食减少约 1/3，先吃蔬菜和蛋白，再吃主食。",
  },
  {
    category: "sleep",
    title: "睡眠",
    detail: "今晚 23:30 前上床，睡前 30 分钟不再刷短视频。",
  },
  {
    category: "exercise",
    title: "运动",
    detail: "饭后约 30 分钟开始散步，体力不足时先走 15-20 分钟。",
  },
  {
    category: "stress",
    title: "压力",
    detail: "做 3 分钟呼吸练习，把压力状态记录为“紧绷/平稳”。",
  },
  {
    category: "energy",
    title: "精力",
    detail: "下午避免含糖饮料，用无糖茶或温水替代。",
  },
];

export const analysisSamples = {
  report: {
    title: "体检/OGTT 报告解读",
    summary: "这份样例报告里，餐后 2 小时血糖和 HbA1c 值得重点关注。",
    risk_level: "orange",
    confidence: "medium",
    result: {
      fields: [
        { label: "HbA1c", value: "6.1%", note: "接近糖前期常见关注区间，建议结合医生意见复查。" },
        { label: "空腹血糖", value: "5.8 mmol/L", note: "略高，需结合近期睡眠和饮食观察。" },
        { label: "餐后 2 小时血糖", value: "8.6 mmol/L", note: "餐后波动偏高，适合记录餐食和餐后反应。" },
        { label: "甘油三酯", value: "1.9 mmol/L", note: "可作为代谢风险辅助观察指标。" },
      ],
      focus: ["餐后波动偏高", "睡眠不足可能影响胰岛素敏感性", "建议复查并咨询医生确认"],
      suggestions: {
        diet: "晚餐主食减少约 1/3，先吃蔬菜和蛋白，再吃主食。",
        sleep: "今晚 23:30 前上床，睡前 30 分钟不再刷短视频。",
        exercise: "饭后约 30 分钟开始散步，体力不足时先走 15-20 分钟。",
        stress: "做 3 分钟呼吸练习，把压力状态记录为“紧绷/平稳”。",
        energy: "下午避免含糖饮料，用无糖茶或温水替代。",
      },
      medical_boundary: "本结果用于健康教育与生活方式行为支持，不替代医生诊断和治疗。",
    },
  },
  meal: {
    title: "餐盘分析",
    summary: "这份午餐主食比例偏高，蔬菜略少，建议做低门槛替换。",
    risk_level: "yellow",
    confidence: "medium",
    result: {
      plate: {
        staple: "白米饭约一碗",
        protein: "鸡蛋和少量鸡肉",
        vegetables: "绿叶菜偏少",
        drink: "无明显含糖饮品",
        cooking: "家常炒制",
      },
      carbRisk: "中",
      observations: ["精制主食占比偏高", "蔬菜量不足", "蛋白质可以保留"],
      swaps: ["米饭减少约 1/3", "增加一份绿叶菜", "饭后约 30 分钟开始轻松步行"],
      medical_boundary: "餐盘分析是估计结果，用于行为建议，不提供诊断或治疗结论。",
    },
  },
  label: {
    title: "配料表分析",
    summary: "这款食品添加糖位置靠前，更适合偶尔少量，不建议作为每日加餐。",
    risk_level: "yellow",
    confidence: "medium",
    result: {
      purchaseAdvice: "需控制",
      reasons: ["添加糖相关词靠前", "膳食纤维偏低", "蛋白质含量不突出"],
      alternatives: ["优先选择无糖酸奶", "选择原味坚果并控制份量", "选择高蛋白低糖加餐"],
      boundary: "偶尔少量可以，尽量不要作为每日固定加餐。",
      medical_boundary: "配料表建议用于消费选择参考，不替代医生或营养师建议。",
    },
  },
};

export const content = {
  importedFrom: "https://glucolit.vercel.app/zh",
  importedAt: "2026-07-03",
  guides: [
    {
      title: "糖前基础",
      label: "Prediabetes 101",
      source: "指南",
      summary: "解释糖尿病前期、OGTT、HbA1c、空腹血糖和不同糖前亚型，帮助读者判断自己处在哪个风险阶段。",
      keywords: ["糖前基础", "诊断标准", "风险阶段"],
      originPath: "/guide/prediabetes",
      url: "https://glucolit.vercel.app/zh/guide/prediabetes",
    },
    {
      title: "CGM 监测",
      label: "Glucose tracking",
      source: "指南",
      summary: "用动态血糖理解个人化餐后反应，讨论 CGM 是否适合糖前、如何避免数据焦虑、哪些指标最值得看。",
      keywords: ["CGM", "餐后反应", "动态血糖"],
      originPath: "/guide/cgm",
      url: "https://glucolit.vercel.app/zh/guide/cgm",
    },
    {
      title: "饮食干预",
      label: "Diet",
      source: "指南",
      summary: "聚焦蛋白质、膳食纤维、低 GI 主食、进食顺序、补充剂和体重管理，先给可执行清单，再放研究证据。",
      keywords: ["饮食结构", "低 GI", "进食顺序"],
      originPath: "/guide/diet",
      url: "https://glucolit.vercel.app/zh/guide/diet",
    },
    {
      title: "运动睡眠",
      label: "Exercise / Sleep",
      source: "指南",
      summary: "聚焦饭后步行、有氧、抗阻训练、肌肉量、身体成分、睡眠节律和恢复，把运动睡眠拆成可执行路线。",
      keywords: ["饭后步行", "抗阻训练", "睡眠节律"],
      originPath: "/guide/exercise-sleep",
      url: "https://glucolit.vercel.app/zh/guide/exercise-sleep",
    },
    {
      title: "情绪管理",
      label: "Stress / Emotion",
      source: "指南",
      summary: "追踪压力、情绪、睡眠质量、皮质醇和行为坚持度，帮助读者理解心理状态如何影响血糖与代谢。",
      keywords: ["压力", "情绪", "行为坚持"],
      originPath: "/guide/stress-emotion",
      url: "https://glucolit.vercel.app/zh/guide/stress-emotion",
    },
    {
      title: "代谢健康",
      label: "Metabolic health",
      source: "指南",
      summary: "把肝脏脂肪、胰岛素敏感性、血脂、炎症、身体成分和长期疾病风险放在同一张代谢地图里。",
      keywords: ["胰岛素敏感性", "血脂", "身体成分"],
      originPath: "/guide/metabolic-health",
      url: "https://glucolit.vercel.app/zh/guide/metabolic-health",
    },
  ],
  articles: [
    {
      title: "睡眠呼吸暂停与前糖尿病：CPAP 治疗的新视角",
      subtitle: "Prediabetes and Sleep Apnea: A New Perspective on CPAP Therapy",
      source: "PubMed insulin resistance interventions via PubMed (Sleep medicine)",
      date: "2026-06-27",
      evidence: "专家",
      tags: ["医学研究", "糖尿病前期", "生活方式", "胰岛素抵抗"],
      summary: "睡眠呼吸暂停可能与前糖尿病人群的疲倦、打鼾、白天精神不振和代谢风险相关，原文重点提示睡眠问题需要被纳入整体观察。",
      originPath: "/articles/prediabetes-and-obstructive-sleep-apnea-a-review-of-the-pathophysiologic-efb885b1",
      url: "https://glucolit.vercel.app/zh/articles/prediabetes-and-obstructive-sleep-apnea-a-review-of-the-pathophysiologic-efb885b1",
    },
    {
      title: "菲律宾中年和老年人中孤立性收缩期高血压的普遍性及风险因素",
      subtitle: "Prevalence and Risk Factors of Isolated Systolic Hypertension Among Middle-Aged and Older Adults in the Philippines",
      source: "PubMed prediabetes lifestyle intervention via PubMed (Blood pressure)",
      date: "2026-06-24",
      evidence: "观察",
      tags: ["医学研究", "糖尿病前期", "生活方式"],
      summary: "研究关注中老年人孤立性收缩期高血压的普遍性及风险因素，提醒代谢健康观察不应只看单一血糖指标。",
      originPath: "/articles/prevalence-and-factors-associated-with-isolated-systolic-hypertension-am-3bcce78c",
      url: "https://glucolit.vercel.app/zh/articles/prevalence-and-factors-associated-with-isolated-systolic-hypertension-am-3bcce78c",
    },
    {
      title: "糖尿病前期与神经病变风险：哈萨克斯坦十年纵向研究启示",
      subtitle: "Prediabetes and the Risk of Neuropathy: Insights from a Decade-Long Study in Kazakhstan",
      source: "PubMed diabetes prevention and remission via PubMed (Future science OA)",
      date: "2026-06-20",
      evidence: "药物研究",
      tags: ["医学研究", "糖尿病前期", "生活方式"],
      summary: "这项十年纵向研究把代谢性疾病与周围神经病变风险放在一起观察，强调早期管理和持续随访的重要性。",
      originPath: "/articles/longitudinal-assessment-of-metabolic-and-neurological-decline-in-periphe-d300e663",
      url: "https://glucolit.vercel.app/zh/articles/longitudinal-assessment-of-metabolic-and-neurological-decline-in-periphe-d300e663",
    },
    {
      title: "遗传与环境因素如何共同影响青少年血糖平衡轨迹",
      subtitle: "Interplay of Genetics and Environment in Glucose Homeostasis Trajectories Among Youth",
      source: "国际医学期刊",
      date: "2026-06-17",
      evidence: "专家",
      tags: ["医学研究", "糖尿病前期", "生活方式"],
      summary: "文章讨论遗传和环境因素如何共同影响青少年血糖平衡轨迹，为早期预防糖前期和 2 型糖尿病提供观察角度。",
      originPath: "/articles/nature-vs-nurture-of-glucose-homeostasis-trajectories-in-children-from-t-cf7e60fe",
      url: "https://glucolit.vercel.app/zh/articles/nature-vs-nurture-of-glucose-homeostasis-trajectories-in-children-from-t-cf7e60fe",
    },
    {
      title: "社会经济地位与糖尿病前期进展风险的关联研究",
      subtitle: "Socioeconomic Status Linked to Progression from Prediabetes to Diabetes",
      source: "国际医学期刊",
      date: "2026-06-16",
      evidence: "观察",
      tags: ["医学研究", "糖尿病前期", "生活方式"],
      summary: "基于 UK Biobank 的前瞻性队列研究，探讨社会经济地位与糖尿病前期人群进展风险之间的关系，并分析生活方式因素的作用。",
      originPath: "/articles/association-of-socioeconomic-status-and-lifestyle-factors-with-incident-8821957b",
      url: "https://glucolit.vercel.app/zh/articles/association-of-socioeconomic-status-and-lifestyle-factors-with-incident-8821957b",
    },
    {
      title: "肌肉与内脏脂肪比例对糖尿病前期风险的影响",
      subtitle: "The Impact of Muscle-to-Visceral Fat Ratio on Prediabetes Risk",
      source: "国际医学期刊",
      date: "2026-06-15",
      evidence: "专家",
      tags: ["医学研究", "糖尿病前期", "生活方式"],
      summary: "研究提示肌肉与内脏脂肪比例可能比体重更能反映糖尿病前期风险，适合作为身体成分观察方向。",
      originPath: "/articles/higher-appendicular-skeletal-muscle-mass-to-visceral-fat-area-ratio-asso-cf57bdc8",
      url: "https://glucolit.vercel.app/zh/articles/higher-appendicular-skeletal-muscle-mass-to-visceral-fat-area-ratio-asso-cf57bdc8",
    },
    {
      title: "糖尿病前期成人改变生活方式可降低多重共病风险",
      subtitle: "Lifestyle Changes in Adults with Prediabetes May Reduce the Risk of Multimorbidity",
      source: "PubMed prediabetes lifestyle intervention via PubMed (JAMA)",
      date: "2026-06-15",
      evidence: "专家",
      tags: ["医学研究", "糖尿病前期", "生活方式", "药物研究"],
      summary: "研究关注糖尿病前期成人的生活方式改变与多重共病风险之间的关系，适合转化为低门槛行为实验和长期记录。",
      originPath: "/articles/lifestyle-and-metformin-interventions-and-risk-of-multimorbidity-in-adul-40d69bf0",
      url: "https://glucolit.vercel.app/zh/articles/lifestyle-and-metformin-interventions-and-risk-of-multimorbidity-in-adul-40d69bf0",
    },
    {
      title: "糖尿病前期与心血管健康：生活方式干预的新视角",
      subtitle: "Prediabetes and Cardiovascular Health: A New Perspective on Lifestyle Interventions",
      source: "国际医学期刊",
      date: "2026-06-09",
      evidence: "专家",
      tags: ["医学研究", "糖尿病前期", "生活方式"],
      summary: "文章探讨糖尿病前期与心血管健康之间的关系，并关注通过生活方式干预改善血糖水平对心血管风险的潜在影响。",
      originPath: "/articles/glycemic-control-and-cardiovascular-health-in-prediabetes-untiring-explo-b96eac3d",
      url: "https://glucolit.vercel.app/zh/articles/glycemic-control-and-cardiovascular-health-in-prediabetes-untiring-explo-b96eac3d",
    },
    {
      title: "国家糖尿病预防计划对糖尿病前期成人的影响",
      subtitle: "Impact of the National Diabetes Prevention Program on Adults with Prediabetes",
      source: "国际医学期刊",
      date: "2026-06-02",
      evidence: "专家",
      tags: ["医学研究", "糖尿病前期", "生活方式"],
      summary: "研究观察国家糖尿病预防计划对糖尿病前期成人进展风险的影响，适合作为结构化生活方式干预的参考案例。",
      originPath: "/articles/progression-to-diabetes-by-adults-with-prediabetes-who-use-the-national-36132a68",
      url: "https://glucolit.vercel.app/zh/articles/progression-to-diabetes-by-adults-with-prediabetes-who-use-the-national-36132a68",
    },
  ],
  cases: [
    "连续三天只完成饭后 15 分钟步行，用户重新找回记录节奏。",
    "把含糖饮料替换成无糖茶后，用户开始关注下午精力变化。",
  ],
  event: {
    title: "7 天餐后行动挑战",
    summary: "用一周时间记录晚餐、餐后步行和第二天空腹状态。",
  },
};
